### ISSUE TITLE
Error on launching the game

### ISSUE THREAD

**Issue by igorunderplayer** [Starciad/StardustSandbox#45]
# Bug Report

## Problem Description

Unhandled exception on launching caused by display.

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.Graphics.GraphicsAdapter.get_CurrentDisplayMode()
   at StardustSandbox.Core.IO.Files.Settings.SVideoSettings.GetMonitorResolution() in X:\x\Projects\StardustSandbox\src\SS.Core\IO\Files\Settings\SVideoSettings.cs:line 57
   at StardustSandbox.Core.IO.Files.Settings.SVideoSettings..ctor() in X:\x\Projects\StardustSandbox\src\SS.Core\IO\Files\Settings\SVideoSettings.cs:line 45
   at StardustSandbox.Core.Managers.IO.SSettingsManager.<>c.<.cctor>b__12_1() in X:\x\Projects\StardustSandbox\src\SS.Core\Managers\IO\SSettingsManager.cs:line 27
   at StardustSandbox.Core.Managers.IO.SSettingsManager.EnsureSettingsFileExists(Type type) in X:\x\Projects\StardustSandbox\src\SS.Core\Managers\IO\SSettingsManager.cs:line 109
   at StardustSandbox.Core.Managers.IO.SSettingsManager.Initialize() in X:\x\Projects\StardustSandbox\src\SS.Core\Managers\IO\SSettingsManager.cs:line 44
   at StardustSandbox.Game.SProgram.Main() in X:\x\Projects\StardustSandbox\src\SS.Game\SProgram.cs:line 32
[1]    4802 IOT instruction (core dumped)  ./StardustSandbox
```

## Steps to Reproduce

1. Just tried to open via terminal

## Environment Information

- **Operating System:** Arch btw
- **Browser/Platform:** Desktop Linux
- **Other Relevant Settings:** tested on gnome, cosmic and hyprland enviroments (all using two monitors, one of them being ultrawide).

**Comment by Starciad** [comment]
Thank you for reporting this bug. After digging into the code, I was able to identify the root cause of the issue. With a subtle adjustment to the configuration file structure, the problem has been resolved.

The issue was caused by the use of the static property `DefaultAdapter.CurrentDisplayMode`, which, due to some internal problems, was triggering exceptions. This has been replaced with the `Adapter` instance available in `GraphicsDevice`, which, after a few minor adjustments, allowed everything to be configured and initialized correctly.

My gratitude for pointing out this rather vexing issue.
